![imagen](./img/ejercicios.png)

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [22]:
import numpy as np

my_array = np.arange(0,10)
print(my_array)

print(my_array[::-2])

[0 1 2 3 4 5 6 7 8 9]
[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [24]:
print(my_array[-2:-4:-1])
print(my_array[8:6:-1])

[8 7]
[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [27]:
print(my_array[2::-1])
print(np.flip(my_array[0:3]))

[2 1 0]
[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [28]:
ejer_4 = np.arange(1,21).reshape(4,5)
print(ejer_4)

print(ejer_4[::-1, ::-1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [30]:
print(ejer_4[:2, :2])

[[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [14]:
print(ejer_4[::2, ::2])

[[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [24]:
print(ejer_4[:3, ::-1])

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [31]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
mask = np.array([True, False, False, True, False])
x[mask]

array(['Loro', 'Loro'], dtype='<U5')

In [32]:
mask = (x == 'Loro')
mask
x[mask]

array(['Loro', 'Loro'], dtype='<U5')

In [7]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
x[np.where(x == 'Loro')]

array(['Loro', 'Loro'], dtype='<U5')

In [8]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
x[x == 'Loro']

array(['Loro', 'Loro'], dtype='<U5')

## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [17]:
ejer_9 = np.arange(20)
ejer_9.reshape(2,5,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [10]:
ejer_4[::-1, ::-1]

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [35]:
ejer_11 = np.zeros(10)
print(ejer_11)

print(ejer_11.itemsize)
print(ejer_11.nbytes)
                   
ejer_11[3] = 1
print(ejer_11)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
8
80
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [36]:
ejer_12 = np.arange(10,50)
print(ejer_12[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [37]:
ejer_13 = np.array([1,2,0,0,4,0])
print(ejer_13)

print(np.where(ejer_13 != 0))

np.nonzero(ejer_13)

[1 2 0 0 4 0]
(array([0, 1, 4], dtype=int64),)


(array([0, 1, 4], dtype=int64),)

## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [38]:
ejer_14 = np.random.randint(1, 100, size = (10,10))
print(ejer_14)

print(np.min(ejer_14))
print(np.max(ejer_14))

[[70 15 59 66 19 93 68 77 45 33]
 [47 62 84 41 59 57 60 51 68 48]
 [26 65 97 82 97 15 58 63 57 92]
 [76 26 73 18 29 25 21 85 10 24]
 [38 88 30 64 66 22 46 75 96 18]
 [25 87 37 84 57 43 71  2 26 12]
 [25 18 33 37 86 40 31 32 23 17]
 [39 41  9 87 49 20 64 26 68 85]
 [23 20  5  2 70 14 58 95 63 84]
 [65  9  7 15 30 18 27 35 60 78]]
2
97


## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [12]:
ejer_15 = np.random.randint(100, size = (30))
print(ejer_15)

print(np.mean(ejer_15))

[38 91 63 49 70 31 20 88 94 90  5 22 70 64  1 91 10 55 96 72 53 65 51 26
 83  8 46 14  9 73]
51.6


## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quiras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [40]:
ejer_16 = np.ones((10,5))
ejer_16[1:-1, 1:-1] = 0
print(ejer_16)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [42]:
ejer_17 = np.zeros((8,8))
ejer_17[1::2, ::2] = 1
ejer_17[::2, 1::2] = 1
print(ejer_17)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [44]:
ejer_18 = np.array([[0,1], [1,0]])
np.tile(ejer_18,(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

## Ejercicio 19
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [45]:
np.random.seed(1)
ejer_19 = np.random.randint(1, 20, (5,5))
print(ejer_19)

ejer_19_mean = np.mean(ejer_19)
ejer_19_std = np.std(ejer_19)

print(ejer_19_mean)
print(ejer_19_std)

(ejer_19 - ejer_19_mean) / ejer_19_std

[[ 6 12 13  9 10]
 [12  6 16  1 17]
 [ 2 13  8 14  7]
 [19  6 19 12 11]
 [15 19  5 10 18]]
11.2
5.138093031466052


array([[-1.01204863,  0.15569979,  0.35032452, -0.42817442, -0.23354968],
       [ 0.15569979, -1.01204863,  0.93419873, -1.98517231,  1.12882347],
       [-1.79054757,  0.35032452, -0.62279916,  0.54494926, -0.81742389],
       [ 1.51807294, -1.01204863,  1.51807294,  0.15569979, -0.03892495],
       [ 0.739574  ,  1.51807294, -1.20667336, -0.23354968,  1.32344821]])

## Ejercicio 20
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya todos los elementos entre el 3 y el 8, por el valor -1
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [49]:
ejer_20 = np.arange(0,11)
print(ejer_20)

y = ejer_20.copy()
# 2. Crea un nuevo array, que parta del anterior, pero sustituya todos los elementos entre el 3 y el 8, por el valor -1
y[(y > 3) & (y<=8)] = -1
print(y)
# np.where(mask, -1, y)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3 -1 -1 -1 -1 -1  9 10]


In [50]:
# 3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8
y = ejer_20.copy()
y[(y > 3) & (y<=8)] *= -1
print(y)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


## Ejercicio 21 (OPCIONAL SI VAN A HACER HUNDIR LA FLOTA)
#### Bonus track. Mini hundir la flota
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**TIP apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.

In [18]:
import numpy as np
import random

In [14]:
# 1. Crea un tablero de 10x10 relleno del carácter espacio ( )

tablero = np.full((10,10), ' ')
print(tablero)

[[' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']]


In [15]:
# 2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas

## barco 1
tablero[0:2:, 1] = 'O'

## barco 2
tablero[1, 3:7] = 'O'

print(tablero)

[[' ' 'O' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' 'O' ' ' 'O' 'O' 'O' 'O' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']]


In [16]:
# 3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X

tablero[0,1] = 'X'

print(tablero)

[[' ' 'X' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' 'O' ' ' 'O' 'O' 'O' 'O' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']]


In [17]:
# 4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -

tablero[0,0] = '-'

print(tablero)

[['-' 'X' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' 'O' ' ' 'O' 'O' 'O' 'O' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']]


In [20]:
# 5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero de manera ALEATORIA.

eslora = 4

while True:
    
    orient = random.choice(['N', 'S', 'E', 'O'])
    current_pos = np.random.randint(10, size = 2)
    
    fila = current_pos[0]
    col = current_pos[1]
    
    coors_posiN = tablero[fila:fila - eslora:-1, col]
    coors_posiE = tablero[fila, col:col + eslora]
    coors_posiS = tablero[fila:fila + eslora, col]
    coors_posiO = tablero[fila, col:col - eslora:-1]
    
    if (orient == 'N') and (len(coors_posiN) == eslora) and ('O' not in coors_posiN): # if (orient == 'N') and (-1 <= fila - eslora < 10) and ('O' not in coors_posiN):
        
        tablero[fila:fila - eslora:-1, col] = 'O'
        break
    
    elif (orient == 'E') and (len(coors_posiE) == eslora) and ('O' not in coors_posiE):
        
        tablero[fila, col:col + eslora] = 'O'
        break
        
    elif (orient == 'S') and (len(coors_posiS) == eslora) and ('O' not in coors_posiS):
        
        tablero[fila:fila + eslora, col] = 'O'
        break
        
    elif (orient == 'O') and (len(coors_posiO) == eslora) and ('O' not in coors_posiO):
        
        tablero[fila, col:col - eslora:-1]
        break
    
    print(orient)
    print(current_pos)
    break

S
[4 4]
